name: Build Windows EXE

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_build.txt

    - name: Build EXE with PyInstaller
      run: |
        pyinstaller --name=JunayDownloader --onefile --windowed --clean junay_downloader.py

    - name: Upload EXE as artifact
      uses: actions/upload-artifact@v3
      with:
        name: JunayDownloader-Windows
        path: dist/JunayDownloader.exe
        retention-days: 90
